import React, { useEffect, useState } from 'react';
import { tradingApi } from '../services/api/tradingApi';
import StockChart from '../components/StockChart';
import './StockDetails.css';

export default function StockDetails({ symbol }: { symbol: string }) {
  const [data, setData] = useState<any>(null); const [error, setError] = useState('');
  useEffect(() => { setData(null); setError(''); tradingApi.stock(symbol).then(setData).catch(() => setError('تعذر تحميل بيانات السهم')); }, [symbol]);
  if (error) return <div className="detail-error">{error}</div>;
  if (!data) return <div className="state">جاري تحميل {symbol}...</div>;
  const q = data.quote || {}, r = data.ranking || {}, ai = data.ai_analysis || {}, change = Number(q.change_percent || 0), indicators = data.technical?.indicators || {}, signals = data.technical?.signals || {};
  const aiScore = Number(ai.score || 0);
  return <section className="stock-details"><div className="stock-details__header"><button onClick={() => window.history.back()}>عودة</button><div><h1>{symbol}</h1><span className="detail-muted">تحليل كمي وذكاء اصطناعي</span></div></div><article className="detail-card detail-card--hero"><StockChart history={data.history || []} /></article><div className="stock-details__grid"><article className="detail-card detail-card--hero"><h3>التقييم النهائي</h3><div className="detail-value">{Number(r.score || 0).toFixed(1)} / 100</div><p>{r.label || 'لا يوجد تصنيف'}</p></article><article className="detail-card"><h3>السعر</h3><div className="detail-value">${Number(q.price || 0).toFixed(2)}</div><div className={change >= 0 ? 'detail-positive' : 'detail-negative'}>{change.toFixed(2)}%</div></article><article className="detail-card"><h3>Technical</h3><div className="detail-value">{Number(data.technical?.technical_score || 0).toFixed(0)}</div><p className="detail-muted">RSI: {Number(indicators.rsi14 || 0).toFixed(1)}</p><p className="detail-muted">SMA20: {indicators.sma20 ? Number(indicators.sma20).toFixed(2) : '—'} | SMA50: {indicators.sma50 ? Number(indicators.sma50).toFixed(2) : '—'} | SMA200: {indicators.sma200 ? Number(indicators.sma200).toFixed(2) : '—'}</p></article><article className="detail-card"><h3>Liquidity</h3><div className="detail-value">{Number(data.liquidity?.score || 0).toFixed(0)}</div></article><article className="detail-card"><h3>Momentum</h3><div className="detail-value">{Number(data.momentum?.score || 0).toFixed(0)}</div></article><article className="detail-card"><h3>Signals</h3><p>Breakout: {signals.breakout_60d ? 'نعم' : 'لا'}</p><p>Golden Cross: {signals.golden_cross ? 'نعم' : 'لا'}</p><p>Relative Volume: {indicators.relative_volume20 ? Number(indicators.relative_volume20).toFixed(2) + 'x' : '—'}</p></article><article className="detail-card detail-card--hero ai-panel"><h3>🤖 AI Analysis</h3><div className="detail-value">{aiScore.toFixed(1)} / 100</div><p><b>الاتجاه:</b> {ai.trend || '—'}</p><p><b>التوصية:</b> {ai.recommendation || '—'}</p><p>{ai.summary || 'لا يوجد ملخص'}</p><div><b>العوامل الإيجابية</b>{(ai.positives || []).length ? <ul>{ai.positives.map((item: string, i: number) => <li key={i}>{item}</li>)}</ul> : <p className="detail-muted">لا توجد عوامل إيجابية مسجلة.</p>}</div><div><b>المخاطر</b>{(ai.risks || []).length ? <ul>{ai.risks.map((item: string, i: number) => <li key={i}>{item}</li>)}</ul> : <p className="detail-muted">لا توجد مخاطر إضافية مسجلة.</p>}</div></article></div></section>;
}
